### ISSUE TITLE
ConstraintAnalytic API vs. ConstraintSparse API

### ISSUE THREAD

**Issue by joanvallve** [IRI-MobileRobotics/wolf#15]
The changes on the API from ConstraintAnalytic to ConstraintSparse will be important.

While the constructor can stay the same (the amount of StateBlocks* may be augmented), the operator() can not be virtual since the order of the parameters (the residual is the last one), also, it won't be templated.

Look at the proposed API in constraint_analytic.h and let's discuss from that base.

**Comment by joansola** [comment]
OK, but I have not seen the operator() in constraintAnalytic...

**Comment by joanvallve** [comment]
This is one of the API changes.
