### ISSUE TITLE
Local Parameterization in Wolf

### ISSUE THREAD

**Issue by andreucm** [IRI-MobileRobotics/wolf#16]
Create LocalParametrizationBase. Get inspirartion from [here](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres21LocalParameterizationE) but using Eigen::Map's as in/out arguments.

Create LocalParametrizationQuaternion and Homogeneous inheriting from LocalParametrizationBase
In ceres_wrapper folder, create wrappers to each of the above class, inheriting from [ceres::LocalParameterization](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres21LocalParameterizationE) 

In StateBlock add pointer to LocalParametrizationBase to indicate which local param has to be used, and methods:
`bool hasLocalParam()`
`LocalParametrizationBase* getLocalParamPtr()`

**Comment by joansola** [comment]
Creada la classe base.

**Comment by joansola** [comment]
Created LocalParametrizationQuaternion.

See if we work with Map or with pointers or with vectors.

**Comment by joansola** [comment]
Created LocalParametrizationHomogeneous.

**Comment by joanvallve** [comment]
The ceres local parametrization wrapper for local parametrizations should be implemented in order to use the wolf local parametrizations

**Comment by joansola** [comment]
@joanvallve are you going to do the local param in the wrapper? :-D

**Comment by joanvallve** [comment]
Done and pushed. Also added to CeresManager::addStateBlock(). Needs to be tested in a ceres optimization.

**Comment by joansola** [comment]
closing
