### ISSUE TITLE
Remove NodeLinked

### ISSUE THREAD

**Issue by andreucm** [IRI-MobileRobotics/wolf#18]
Remove NodeLinked and check its implications :
- remove NodeTerminus
- Reimplement getTop() to all derived classes
- id factory for each node type

**Comment by joanvallve** [comment]
this implies the elimination of getTop() method also

**Comment by joansola** [comment]
I am actually thinking on leaving NodeLinked in. I am actually inclined to improve its design, although by now I'll leave it as it is. We can re-discuss it.

**Comment by joansola** [comment]
closing. Will reopen if we find it useful in the future.
