### ISSUE TITLE
Processors, Trackers

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#21]
See what to do:
 - ProcessorBase uses extractFeatures() and establishConstraints()
 - ProcessorTracker uses track()
 - ProcessorMotion uses integrate()

They have similar meanings but... we need to clarify all this.

**Comment by joansola** [comment]
The design of ProcessorBase is probably not going to last, at least as a base class for the others.

**Comment by joansola** [comment]
We need a clear policy for managing the frames that are not yet keyframes.
- Are Frames in the Trajectory:
  - Is there just one frame
  - Or are there two Frames, last and incoming?
- Are Frames in the Tracker?

We need also a clear policy of how to transition from Tracked Frames to KeyFrames.
- Who can create key-frames? Who can crate non-key Frames?

**Comment by joansola** [comment]
TODOs:
- How do we create new Keyframes (in WolfProblem ? )
- How do we create new Landmarks (in WolfProblem ?)
- How to deal with autonomous / slave Trackers ?

**Comment by joanvallve** [comment]
ProcessorMotion:

After creating a KeyFrame, transfer the motion buffer as features (Delta_X) in the capture and methods interpolate(capture, timestamp) and concatenate(capture,capture) should be in the processor too.

**Comment by joansola** [comment]
This issue keeps alive in issue #31 .  Closing.
