### ISSUE TITLE
Check possible bug at Lines 174-179 of file constraint_gps_pseudorange_2D.h

### ISSUE THREAD

**Issue by andreucm** [IRI-MobileRobotics/wolf#26]
Check possible bug at Lines 174-179 of file constraint_gps_pseudorange_2D.h.
Take into account that latitude angle is not right-handed with respect to ECEF, so check exchanging the sign in both the sinus terms of the matrix T_lat2lon.

**Comment by pt07** [comment]
if I change the sign in the sinus, the z-axis of the final frame is no more aligned to the line that goes through ecef origin and base link origin.
