### ISSUE TITLE
pseudorange_ at line 222 of file constraint_gps_pseudorange_2D.h

### ISSUE THREAD

**Issue by andreucm** [IRI-MobileRobotics/wolf#28]
At line 222 we find: 
`_residual[0] = (distance + _bias[0] * T(LIGHT_SPEED)) - (pseudorange_);`

why `pseudorange_`  is not `T(pseudorange_)` ?

**Comment by pt07** [comment]
i don't know, i forgot it. but is not needed, it's like this also in in my trilateration library and is working, without compile problems. anyway i just added it, just to be sure
