### ISSUE TITLE
function getTop()

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#3]
Is it really necessary? Can we rename it to getProblem()? Then we can simplify some things:
-  location_ in NodeLinked not necessary
-  location_ in WolfProblem not necessary

**Comment by joansola** [comment]
I think if this is really needed we should overload it with a more efficient implementation. But the issue here, by now, is renaming it.

**Comment by joanvallve** [comment]
I would fuse this issue with the nodeLinked elimination
