### ISSUE TITLE
Bug in TimeStamp ?

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#32]
void TimeStamp::set(const unsigned long int sec, const unsigned long int nanosec)
{
    time_stamp_ = (WolfScalar)(sec + nanosec / 1e9);
}

Should this (WolfScalar) cast be done so that the division is done at float level and not integer?

**Comment by andreucm** [comment]
Yes ! Absolutely! 
commit 564e4b2ea58b3a276ec533cfc9b75e566ae5f122 
and pushed!

thanks!
