### ISSUE TITLE
ProcessorTracker initialization

### ISSUE THREAD

**Issue by joanvallve** [IRI-MobileRobotics/wolf#37]
Shouldn't this function call detectNewFeatures(), createLandmarks...? Is the first frame a keyframe?

**Comment by joansola** [comment]
Uhm maybe yes... it makes sense!

**Comment by joanvallve** [comment]
Should a processor be initialized? maybe it should auto-initialize itself when a keyframe is created, we should implement this keyFrameCreation callback from the outside

**Comment by joansola** [comment]
On keyframe creation, the tracker should be reset, not initialized. It's not exactly the same.

**Comment by joanvallve** [comment]
I'll rephrase:

> Should a processor be initialized? maybe it should auto-initialize itself when **the first** keyframe is created, we should implement this keyFrameCreation callback from the outside

**Comment by joansola** [comment]
I fixed many things in init(), and now we are detecting new Features and adding them on origin_ptr.

Waiting to see how it works before closing.
