### ISSUE TITLE
ProcessorTrackerFeature::processNew() constraint creation

### ISSUE THREAD

**Issue by joanvallve** [IRI-MobileRobotics/wolf#40]
The creation of constraints after tracking the new features from `last_ptr_` to `origin_ptr_`is missing.

**Comment by joansola** [comment]
You can add it as appropriate. The method is pure virtual in ProcessorTracker, and the derived classes know which kind of constraint to create.

**Comment by joanvallve** [comment]
Yes, it is a TODO issue (TBC by you) after being able to receive the correspondences from track() ([issue #39](https://github.com/IRI-MobileRobotics/wolf/issues/39))

**Comment by joansola** [comment]
In processNew(), I added establishConstraints() just before detectNewFeaures(), so that constraints are only between Features in Last and Origin. the newly detected ones are not constrained.
