### ISSUE TITLE
Doubt on deleting pointer

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#43]
````
ProcessorTracker::~ProcessorTracker()
{
    // FIXME: This test with nullptr is not fail safe. Only the class design can make it safe, by ensuring
    // at all times that whenever incoming_ptr_ is not used, it points to nullptr.
    // See both flavors of reset(), and advance().
    if (incoming_ptr_ != nullptr)
        delete incoming_ptr_;
}
````
@joanvallve can you comment on this FIXME here?
  - If OK, I'd like to remove the FIXME.
  - If we can do better, then let's discuss it.

**Comment by joanvallve** [comment]
At least, we should use destruct()...

Maybe, it would be better to check if it points to the same as last or origin.. or, easier, if it has no upper_node
