### ISSUE TITLE
Remove computeFramePose() from CaptureBase

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#47]
We are very close to do this because we are now working on the Motion processors.

This issue is just to have a stronger reminder than a mere TODO in the code.

**Comment by joansola** [comment]
Hi. After all the advances in motion_laser, are we ready to fix this one?

**Comment by joanvallve** [comment]
Yes, we are ready..

**Comment by joansola** [comment]
In master? Or in motion_laser branch?

**Comment by joanvallve** [comment]
...in motion_laser or after merging motion_laser to master

**Comment by joansola** [comment]
Done ! Finally!!!
