### ISSUE TITLE
minor: 2D or 2d in class names and file names

### ISSUE THREAD

**Issue by joanvallve** [IRI-MobileRobotics/wolf#48]

**Comment by joansola** [comment]
You can have a hyothetical class name with something after the d...:

    Odom3dFeature

or 

    Odom3DFeature

Which one is better? Well, I don't care actually.

**Comment by joansola** [comment]
Answer:  We'll use uppercase D

**Comment by joansola** [comment]
Answer : we'll use uppercase D
