### ISSUE TITLE
Wolf's logo

### ISSUE THREAD

**Issue by pt07** [IRI-MobileRobotics/wolf#49]
Is this Wolf's official logo?

![red-wolf](https://cloud.githubusercontent.com/assets/4237799/14570608/78ea4c8e-0345-11e6-8c57-dde9f2293995.png)

Can I use it in the slide for the thesis defence?

Sorry if I opened this issue, but it is the fastest way to ask you all a question.

**Comment by joansola** [comment]
Hi Pier.

The logo is not ours, I took from the internet and it belongs to some other organization or designer. However, I think you can use it in the defence -- I would not use it in your public documents.

Best

**Comment by pt07** [comment]
My only public document will be the report, and it's without logos.
If I'll need one to fill the Wolf slide, i'll use this, thank you!

Regards

**Comment by joanvallve** [comment]
I quickly made 2 silly logos.. If one of them is good for you we can take it as temporary logo, feel free to propose modifications and for sure to say you don't like them at all! I like the first one

![logo1](https://cloud.githubusercontent.com/assets/7301169/14598868/9b1a11ca-0554-11e6-84a3-4c7670f9f1f4.png)
![logo2](https://cloud.githubusercontent.com/assets/7301169/14598866/99520456-0554-11e6-9dd5-5a376a4048f3.png)

**Comment by joansola** [comment]
I prefer the first one!
How'd you do them? :-D

**Comment by andreucm** [comment]
I like both images. Regarding the text part, I would avoid to mix font types ...

**Comment by joanvallve** [comment]
Same font types, more serious: 
![wolf_logo](https://cloud.githubusercontent.com/assets/7301169/14674473/72897a28-0704-11e6-93e7-3eae3713e3ee.png)

**Comment by joanvallve** [comment]
Better?
![wolf_logo](https://cloud.githubusercontent.com/assets/7301169/14675533/bebf0890-0709-11e6-8aa3-6a0c3fdcb228.png)

**Comment by joansola** [comment]
I think I would prefer it without the 'windowed localization frames', just WOLF. Like many other brands, who cares.

Besides, and as Jeremie pointed out, we are not necessarily using 'windows' of keyframes, so the W is no longer justified if not by the fact that we like it like this.

**Comment by joanvallve** [comment]
True! I think we are approaching to something simple and cool 
![wolf_logo](https://cloud.githubusercontent.com/assets/7301169/14675833/1c3d2bc2-070b-11e6-9fec-0f7c58d28dcd.png)

**Comment by joansola** [comment]
+1

**Comment by joansola** [comment]
I added the logo to the Doxygen generated html page.

**Comment by joansola** [comment]
Thanis for this one! Closing as this is no longer an issue!
