### ISSUE TITLE
WolfProblem::getStateSize()  not defined

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#51]
This code in WolfProblem:

        /** \brief Gets state size
         */
        const unsigned int getStateSize() const;

The function is declared, but not defined, yet WOLF compiles without problem! I don't understand.

@joanvallve

**Comment by joanvallve** [comment]
Probably, it compiles because it is not called from anywhere... I've checked the history and it is a useless function that wasn't deleted after decentralizing the state from a vector allocated in wolf_problem to several vectors inside the state_blocks. It should be removed.

**Comment by joansola** [comment]
I'll remove it and push to master

**Comment by joansola** [comment]
Done. closing. Thanks
