### ISSUE TITLE
Change WolfProblem to Problem?

### ISSUE THREAD

**Issue by joanvallve** [IRI-MobileRobotics/wolf#52]
In the library, there isn't any other class with "wolf" in the name (apart from wolf_manager, to be removed). After putting the wolf namespace, it is even more redundant... Not urgent.

**Comment by joansola** [comment]
+1

**Comment by joansola** [comment]
The same with WolfConstants (nobody uses but me, it is in wolf.h)

**Comment by joansola** [comment]
I do it, together with WOlfConstants. Will push to master some time soon.

I'll post it here when I push

**Comment by joansola** [comment]
BTW, also WolfScalar will be renamed.

**Comment by joansola** [comment]
Done:
WolfProblem --> Problem (renamed files and #includes accordingly)
WolfScalar --> Scalar
WolfConstants --> Constants

**Comment by joansola** [comment]
Pushing to master and closing

**Comment by joanvallve** [comment]
getWolfProblem() may be renamed also to getProblem()

**Comment by joanvallve** [comment]
In branch laser_motion is already done, when merging it'll be solved
