### ISSUE TITLE
Redesign MotionBuffer by inheriting from list<Motion>

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#56]
all is in the title.

**Comment by joansola** [comment]
According to this

http://stackoverflow.com/questions/2034916/is-it-okay-to-inherit-implementation-from-stl-containers-rather-than-delegate

it is not a good idea to inherit from list<whatever> to add functionality.

Alternatives:
 * Use typedef:
    ````
    typedef list<Motion> MotionBuffer;
    ````
   and use independent functions to add functionality to MotionBuffer.

 * Put list as member and provide const and non-const reference getter
    ````
    class MotionBuffer {
    private:
        list<Motion> container_;
    public:
        const list<Motion>& get() const  {return container_;}
        list<Motion>& get() {return container_;}
        other_method(...) {... }
    }
    ````
    and use the get() to access all the std::list API. Add new methods as appropriate.

@joanvallve what do you think?

**Comment by joanvallve** [comment]
The second alternative is almost what we have now, right? Let's continue like this, then.. removing pushBack() pushFront() etc..

**Comment by joansola** [comment]
This is what I did. And pushed to motion2.
