### ISSUE TITLE
Protect the branch 'master'

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#59]
Hello,

I have protected the master branch so that only me can push there.

Usually, you should do your job in other branches, eventually in forked projects.

To contribute to master, you must send pull requests. First, merge master to your branch, and check that everything goes fine:

````
git checkout my_branch
git merge master
make   --> be sure you compile
../bin/test_xxx  --> execute some tests
````

and when you are sure everything is OK, do a pull request so that I can merge your branch to master.

I hope this works fine.

**Comment by joanvallve** [comment]
We should agree on some tests that should be mandatory to run before the pull request and the output of those tests.
