### ISSUE TITLE
Default rules and/or good practices for inheriting base nodes below NodeLinked

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#6]
Possible rules for the constructor:
  - Casting most used pointers to the derived type

Possible rules for destructors: 
  - Always virtual
  - delete linked nodes (upper, remote)

**Comment by andreucm** [comment]
Solved. 
See an instance at processor_laser_2D.cpp 
ProcessorLaser2D::extractFeatures(CaptureBase* capture_ptr_)

**Comment by joansola** [comment]
We are by now using static casting whenever necessary, not systematically. Closing this issue.
