### ISSUE TITLE
Remove branch motion2

### ISSUE THREAD

**Issue by joansola** [IRI-MobileRobotics/wolf#67]
Please react if you are using this branch at all. I would just remove it.

If you were basing your designs on top of motion2, I just merged it to master. You can keep working on your branches, just from time to time synchronize them with master:

git merge master

@joanvallve , @AtDinesh can you please confirm if I can delete? thanks.

**Comment by joanvallve** [comment]
I'm working in motion_laser, no problem

**Comment by joansola** [comment]
Well, removing 'motion2'...
